services:
  postgres:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=fastapi
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=plantsdb
    ports:
      - "5432:5432"
    networks:
      - app_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fastapi -d plantsdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: something@mail.com
      PGADMIN_DEFAULT_PASSWORD: secret
    ports:
      - "5050:80"
    volumes:
        - pgadmin_data:/var/lib/pgadmin

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./backend/media:/app/media
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - POSTGRES_USER=fastapi
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=plantsdb
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    networks:
      - app_network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  app_network:
    driver: bridge